config/routes.rb
Molitum::Application.routes.draw do
  devise_for :users

  root :to => "static_pages#home"

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :companies 
  resources :users
  resources :customers
  resources :quick_links, only: [:create, :destroy]
  resources :time_clocks, only: [:create, :update, :destroy]

  resources :bids do
    resources :bid_items, only: [:create, :destroy], shallow: true
  end
  
  resources :invoices do
    resources :invoice_items, only: [:create, :destroy], shallow: true
  end
  
  resources :jobs do
    resources :job_expenses, only: [:create, :destroy], shallow: true
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :customer_id, :billing_start, :billing_end, :total_due, :paid
  
  has_many :invoice_items

  belongs_to :customer
  belongs_to :company

  CATEGORIES = ['Demolition', 'Framing', 'Tile', 'Finish Work', 'Plumbing', 'Electrical', 'Other']

  validates :customer_id, presence: true

  def add_to_total_due (amount)
    self.total_due += amount
    self.save
  end

  def subtract_from_total_due (amount)
    self.total_due -= amount
    self.save
  end
  
  def status
    if self.paid
      "Paid"
    else
      "Not Paid"
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :authenticate_user!
  def index
    @invoices = current_user.company.invoices.order("created_at").page(params[:page]).per_page(10)
  end

  def new
    @invoice = Invoice.new
    @customers = Customer.all
  end

  def show
    @invoice = Invoice.find(params[:id])
    @company = @invoice.customer.company
    @invoice_items = @invoice.invoice_items.all
  end

  def edit
    @title = 'Invoices'
    @head = 'Edit'
    @invoice = Invoice.find(params[:id])
  end


  def update
    @invoice = Invoice.find(params[:id])
    @company = @invoice.company
    if @invoice.update_attributes(params[:invoice])
      @company.add_income(@invoice.total_due)
      flash[:success] = "Invoice Updated"
      redirect_to invoice_path(@invoice)
    else
      flash[:error] = "Update Failed"
      render 'edit'
    end
  end

  def create 
    @invoice = Invoice.create(params[:invoice])
    if @invoice.save
      flash[:success] = "Invoice Created"
      redirect_to invoice_path(@invoice)
    else
      flash[:error] = "Invoice Failed"
      render 'new'
    end
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @company = @invoice.customer.company
    @company.add_income(@invoice.total_due)
    if @invoice.destroy
      flash[:success] = "Invoice Deleted"
      redirect_to invoices_path
    else
      flash[:Error] = "Failed to Delete"
      redirect_to :back
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_invoiceform.html.erb
<% provide(:title, "Invoice Setup") %>
<div class="row-fluid">

<div class="span8 form-highlight round padding2">
  <h2>Invoice Setup</h2>
  <div class="line"></div>
  <span class="required_notification">* Denotes Required Field</span>
  </br>
  <%= simple_form_for(@invoice) do |f| %>
    <%= f.error_notification %>
    <%= f.association :customer , include_blank: false, :required => false %>
    <%= f.input :billing_start, :as => :string %>
    <%= f.input :billing_end, :as => :string %>
    <%= f.button :submit, class: "submit btn btn-large btn-primary" %>
  <% end %>
</div>

<div class="span4 border round highlight ">
  <h2>Customer Information</h2>
  <h6>Details</h6>
  </br>
  <h3>Note:</h3>
  <p>The information you are entering here will help you to generate invoices and bids with ease.</p>
</div>

</div>

app/views/invoices/_invoiceitems.html.erb
  <table class="table table-bordered table-condensed" id="invoice_items_form">
  <tr>
    <td class="highlight">Activity</td>
    <td class="highlight">Description</td>
    <td class="highlight" colspan ="2">Amount</td>
  </tr>
  <% if @invoice_items.empty? %>
  <% else %>
    <%  @invoice_items.each do |invoice_item| %>
      <tr>
        <td><%= invoice_item.category %></td>
        <td><%= invoice_item.description %></td>  
        <td ><%= invoice_item.cost %></td>
        <td>
          <% if can? :delete, invoice_item %><%= link_to "Delete", invoice_item_path(invoice_item), method: :delete %></td><% end %>        
      </tr> 
    <% end %>
  <% end %>

  <%= simple_form_for [@invoice, InvoiceItem.new] do |f| %>
  <tr>
    <td>
      <%= f.collection_select :category, Bid::CATEGORIES, :to_s, :to_s, include_blank: false %>
    </td>
    <td>
      <%= f.text_field :description, class: "span4"%>
    </td>
    <td>
      <%= f.text_field :cost, class: "span1" %>
    </td>
    <td>
      <%= f.submit "Add", class: "btn" %>
    </td> 
  </tr>
<% end %>
</table>

app/views/invoices/edit.html.erb
<% provide(:title, "Invoices") %>
<%= render 'invoices/invoiceform' %>

app/views/invoices/index.html.erb
<% provide(:title, "Invoices") %>
<table class="table table-bordered table-condensed shadow">
  <th class="header">Invoices</th>
  <tr>
    <td>
      <table class="table table-bordered table-condensed">
        <% unless @invoices.empty? %>
          <tr>
            <td class="highlight">Created At</td>
            <td class="highlight">Invoice Number</td>
            <td class="highlight">Customer</td>
            <td class="highlight">Status</td>
            <td class="highlight" colspan="2"></td>
          </tr>
          <%  @invoices.each do |invoice| %>
            <tr>
              <td><%= link_to invoice.created_at.to_date, invoice_path(invoice) %></td>
              <td><%= invoice.id %>
              <td><%= link_to invoice.customer.name, customer_path(invoice.customer) %></td>
              <td><%= invoice.status %>
              <td><% if can? :edit, invoice %><%= link_to "Edit", edit_invoice_path(invoice), class: "btn" %><% end %></td>
              <td><% if can? :delete, invoice %><%= link_to "Delete", invoice_path(invoice), confirm: "You Sure?", class: "btn", method: :delete %><% end %></td>
            </tr>
            <% end %>
            <tr>
              <td colspan="6">
                <div class="digg_pagination">
                    <%= will_paginate @invoices, :container => false %>
                </div>
              </td>
            </tr>
        <% else %>
        <tr>
          <td>There are currently no invoices</td>
        </tr>
        <% end %>
        <tr>
          <td colspan="6"><% if can? :create, Invoice.new %><%= link_to "New Invoice", new_invoice_path, class: "btn" %><% end %></td>
        </tr>
      </table>
    </td>
  </tr>
</table>

app/views/invoices/new.html.erb
<% provide(:title, "Invoices") %>
<%= render 'invoices/invoiceform' %>

app/views/invoices/show.html.erb
<% provide(:title, "Invoices") %>
<table class="table table-bordered table-condensed shadow" cellpadding="5">
  <th class="header" colspan="4">Invoice Number: <%= @invoice.id %></th>
  <tr>
    <td>
      <table class="table table-bordered table-condensed">
        <tr>
          <td class="highlight">Customer</td>
          <td class="highlight">Billing Start</td>
          <td class="highlight">Billing End</td>
          <td class="highlight">Status</td>
        </tr>
        <tr>
          <td><%= link_to @invoice.customer.name, customer_path(@invoice.customer) %></td>
          <td><%= @invoice.billing_start.to_date %></td>
          <td><%= @invoice.billing_end.to_date  %>
          <td><%= @invoice.status %></td>
        </tr>
      </table>
      <%= render 'invoices/invoiceitems' %>
      <table class="table table-bordered table-condensed">
        <tr>
          <td width="20%">Total</td>
          <td><%= @invoice.total_due %></td>
        </tr>
        <tr>
          <td colspan="2">
            <%= link_to "Download Invoice (PDF)", invoice_path(@invoice, :format => "pdf"), class: "btn" %>
          </td>
        </tr>
        <tr>
          <% if @invoice.paid == false %>
            <%= form_for(@invoice) do |f| %>
              <td colspan="3">
                <%= f.hidden_field :paid, value: true%>
                <%= f.submit "Mark as Paid", class: "btn btn-primary" %>
              </td>
            <% end %>
          <% end %>
        </tr>
      </table>
    </td>
  </tr>
</table>