config/routes.rb
Molitum::Application.routes.draw do
  devise_for :users

  root :to => "static_pages#home"

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :companies 
  resources :users
  resources :customers
  resources :quick_links, only: [:create, :destroy]
  resources :time_clocks, only: [:create, :update, :destroy]

  resources :bids do
    resources :bid_items, only: [:create, :destroy], shallow: true
  end
  
  resources :invoices do
    resources :invoice_items, only: [:create, :destroy], shallow: true
  end
  
  resources :jobs do
    resources :job_expenses, only: [:create, :destroy], shallow: true
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :subtotal,  :location, :budget, :scope_of_work, :detail_of_work, :total, :labor_cost, :start_date, 
  								:finish_date, :status, :customer_id

  belongs_to :customer

  has_many :job_expenses, dependent: :destroy
  has_many :invoices, dependent: :destroy
  
  validates :customer_id, presence: true
  validates :location, presence: true


	def add_labor_cost(pay_rate, hours)
			self.labor_cost += (pay_rate * hours)
			add_to_total(self.labor_cost)
	end	

	def subtract_labor_cost(pay_rate, hours)
			self.labor_cost -= (pay_rate * hours)
			subtract_from_total(self.labor_cost)
	end

	def add_to_total(amount)
			self.total_cost += amount
			self.save
	end	

	def subtract_from_total(amount)
			self.total_cost -= amount
			self.save
	end

	def remaining_budget
		amount = budget - self.total_cost
	end 

	def check_timeframe_for_job
		if Time.now - finish_date < 1000
			"Ugent"
		else
			"On Schedule"
		end
	end

	def started?
		self.status ==  0 ? false : true 
	end

	def completed?
		self.status ==  4 ? true : false 
	end

	def overdue?
		self.status ==  3 ? true : false
	end

	def on_schedule?
		self.status ==  1 ? true : false
	end

	def status_in_words
		case self.status
			when 0
				"Not Started"
			when 1
				"In Progress"
		 	when 2
		 		"Nearing Completion"
		 	when 3
		 		"Project Overdue"
		 	when 4
		 		"Completed"
		 	else
		 		"An error has occured"
		 	end
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_filter :authenticate_user!
	def index
		@jobs = current_user.company.jobs.order("created_at").page(params[:page]).per_page(10)
	end

	def new
		@job = Job.new
	end

	def show
		@job = Job.find(params[:id])
		@job_expenses = JobExpense.all
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		if @job.update_attributes(params[:job])
			flash[:success] = "Job Updated"
			redirect_to job_path(@job)
		else
			flash[:error] = "Update Failed"
			render 'edit'
		end
	end

	def create	
		@job = Job.create(params[:job])
    if @job.save
      flash[:success] = "Job Created"
      redirect_to job_path(@job)
    else
    	flash[:error] = "Job Failed"
      render 'new'
    end
	end

	def destroy
		Job.find(params[:id]).destroy
		flash[:success] = "Job Deleted"
		redirect_to :back
	end
end

app/helpers/jobs_helper.rb
module JobsHelper

end

app/views/jobs/_budgetinfo.html.erb
<% if @job.budget.present? %>
<div>
	<table class="table table-bordered table-condensed">
		<th class="highlight" colspan="2">Budget Information</th>
		<tr>
			<td width="20%">Budget</td>
			<td><%= @job.budget %></td>
		</tr>
		<tr>
			<td width="20%">Expense</td>
			<td><%= @job.total_cost %></td>
		</tr>
		<tr>
			<td width="20%">Balance</td>
			<td><%= @job.remaining_budget %></td>
		</tr>
	</table>
</div>
<% end %>

app/views/jobs/_jobexpense.html.erb
<table class="table table-bordered table-condensed" id="job_expenses_form">
  <th class="highlight" colspan="4">Job Expenses</th>
  <tr>
    <td>Category</td>
    <td>Description</td>
    <td colspan="2">Cost</td>
  </tr>
  <tr>
    <td>Labor</td>
    <td>Total cost of labor for this job</td>
    <td colspan="2"><%= @job.labor_cost %></td>
  </tr>
  <% if @job_expenses.present? %>
    <% category = "" %>
    <%  @job_expenses.each do |expense| %>
    <tr>
      <% if category != expense.category %>
        <td><%= expense.category %><% category = expense.category %></td>
      <% end %>
      <td><%= expense.description %></td>
      <td><%= expense.cost %></td>  
      <td><% if can? :delete, expense %><%= link_to "Delete", expense, method: :delete, class: "btn"  %></td><% end %>  
    </tr>      
    <% end %>
  <% end %>
	<%= simple_form_for [@job, JobExpense.new] do |f| %>
  	<tr>
      <td>
        <%= f.collection_select :category, JobExpense::CATEGORIES, :to_s, :to_s, include_blank: false %>
      </td>
      <td>
        <%= f.text_field :description %>
      </td>
      <td>
        <%= f.text_field :cost %>
      </td>
      <td>
       	<%= f.submit "Add", class: "btn" %>
      </td>	
    </tr>
  <% end %>
</table>

app/views/jobs/_jobform.html.erb
<% provide(:title, "Job Setup") %>
<div class="row-fluid">

<div class="span8 form-highlight round padding2">
  <h2>Job Setup</h2>
  <div class="line"></div>
  <span class="required_notification">* Denotes Required Field</span>
  </br>
  <%= simple_form_for(@job) do |f| %>
    <%= f.error_notification %>
    <%= f.association :customer, :include_blank => false, :required => false, input_html: { required: "required"} %>
    <%= f.input :location, :required => false %>
    <%= f.input :budget, :required => false %>
    <%= f.input :start_date, :as => :string %>
    <%= f.input :finish_date, :as => :string %>
    <%= f.input :scope_of_work, :as => :text %>
    <%= f.input :detail_of_work, :as => :text %>
    <%= f.button :submit, class: "submit btn btn-large btn-primary" %>
  <% end %>
</div>

<div class="span4 border round highlight ">
  <h2>Customer Information</h2>
  <h6>Details</h6>
  </br>
  <h3>Note:</h3>
  <p>The information you are entering here will help you to generate invoices and bids with ease.</p>
</div>

</div>

app/views/jobs/_jobs.html.erb
<table class="table table-bordered table-condensed">
	<% unless @jobs.empty? %>
		<tr>
			<td class="highlight">Location</td>
			<td class="highlight">Customer</td>
			<td class="highlight">Created</td>
			<td class="highlight" colspan="3">Status</td>
		</tr>
		<%  @jobs.each do |job| %>
			<tr>
				<td><%= link_to job.location, job_path(job) %></td>
				<td><%=link_to job.customer.name, customer_path(job.customer) %></td>
				<td><%= job.created_at.to_date %></td>
				<td width="20%"><%= job.status_in_words %>
				<td><% if can? :edit, job %><%= link_to "Edit", edit_job_path(job), class: "btn" %><% end %></td>
				<td><% if can? :delete, job %><%= link_to "Delete", job_path(job), confirm: "You Sure?", class: "btn", method: :delete %><% end %></td>
			</tr>
			<% end %>
		<tr>
			<td colspan="6">
				<div class="digg_pagination">
         	<%= will_paginate @jobs, :container => false %>
       	</div>
      </td>
		</tr>
	<% else %>
	<tr>
		<td>There are currently no jobs</td>
	</tr>
	<% end %>
	<tr>
		<td colspan="6"><% if can? :edit, Job.new %><%= link_to "New Job", new_job_path, class: "btn" %><% end %></td>
	</tr>
</table>

app/views/jobs/edit.html.erb
<% provide(:title, "Jobs") %>
<%= render 'jobs/jobform' %>

app/views/jobs/index.html.erb
<% provide(:title, "Jobs") %>
<table class="table table-bordered table-condensed shadow">
  <th class="header">Jobs</th>
  <tr>
    <td>
      <%= render 'jobs/jobs' %>
    </td>
  </tr>
</table>

app/views/jobs/new.html.erb
<% provide(:title, "Jobs") %>
<%= render 'jobs/jobform' %>

app/views/jobs/show.html.erb
<% provide(:title, "Jobs") %>
<table class="table table-bordered table-condensed shadow">
  <th class="header">Job Information</th>
  <tr>
    <td>
			<table class="table table-bordered table-condensed">
				<th class="highlight" colspan="4">Job Details</th>
				<tr>
					<td width="20%">Customer</td>
					<td><%= @job.customer.name %></td>
				</tr>
				<tr>
					<td width="20%">Location</td>
					<td><%= @job.location %></td>
				</tr>
				<tr>
					<td width="20%">Status</td>
					<td><%= @job.status_in_words %></td>
				</tr>
				<tr>
					<td width="20%">Start Date</td>
					<td><%= @job.start_date.to_date %></td>
				</tr>
				<tr>
					<td width="20%">Finish Date</td>
					<td><%= @job.finish_date.to_date %></td>
				</tr>
			</table>
			<%= render "jobs/budgetinfo" %>
			<% if @job.started? %>
				<%= render 'jobs/jobexpense' %>
		  <% end %>
		  <table class="table table-bordered table-condensed">
				<tr>
					<% if @job.scope_of_work.present? %>
						<td width="20%">Scope of Work</td>
						<td><%= @job.scope_of_work %></td>
					<% end %>
				</tr>
				<tr>
					<% if @job.detail_of_work.present? %>
						<td width="20%">Detail of Work</td>
						<td><%= @job.detail_of_work %></td>
					<% end %>
				</tr>
			</table>
			<table class="table table-bordered table-condensed">
				<tr>
					<%= form_for(@job) do |f| %>
						<% if @job.started? %>
							<td>
								<%= f.hidden_field :status, :value => 4 %>
					      <%= f.submit "Finish", class: "btn btn-primary" %>
					    </td>
						<% else %>
							<td>
								<%= f.hidden_field :status, :value => 1 %>
					      <%= f.submit "Start", class: "btn btn-primary" %>
					    </td>
					  <% end %>
				  <% end %>
				</tr>
			</table>
		</td>
	</tr>
</table>