config/routes.rb
Molitum::Application.routes.draw do
  devise_for :users

  root :to => "static_pages#home"

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :companies 
  resources :users
  resources :customers
  resources :quick_links, only: [:create, :destroy]
  resources :time_clocks, only: [:create, :update, :destroy]

  resources :bids do
    resources :bid_items, only: [:create, :destroy], shallow: true
  end
  
  resources :invoices do
    resources :invoice_items, only: [:create, :destroy], shallow: true
  end
  
  resources :jobs do
    resources :job_expenses, only: [:create, :destroy], shallow: true
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :name, :address, :email, :city, :state, :zip, :phone
  
  has_many :jobs, dependent: :destroy
  has_many :bids, dependent: :destroy
  has_many :invoices, dependent: :destroy
  belongs_to :company

  validates :name,  presence: true, length: { maximum: 50 }

  def add_labor_hours(hours)
  	self.time += hours
  end

  def full_address
    self.address + "  |  " + self.city + ", " + self.state + ", " + self.zip.to_s 
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_filter :authenticate_user!
	def index
		@customers = current_user.company.customers.order("name").page(params[:page]).per_page(10)
	end

	def new
		@customer = Customer.new
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		if @customer.update_attributes(params[:customer])
			flash[:success] = "Customer Updated"
			redirect_to customers_path
		else
			flash[:error] = "Update Failed"
			render 'edit'
		end
	end

	def create
		@company = current_user.company	
		@customer = @company.customers.create(params[:customer])
	    if @customer.save
	      flash[:success] = "Customer Created"
	      redirect_to customer_path(@customer)
	    else
	    	flash[:error] = "Customer Failed"
	      render 'new'
	    end
	end

	def destroy
		if Customer.find(params[:id]).destroy
			flash[:success] = "Customer Deleted"
			redirect_to customers_path
		else
			flash[:success] = "Delete Failed"
			redirect_to :back
		end
	end
end

app/helpers/customers_helper.rb
module CustomersHelper

	def remember_customer(customer)
		session[:customer_token] = customer.id
	end

	def current_customer
		session[:customer_token]
	end

end

app/views/customers/_bidinfo.html.erb
<table class="table table-bordered table-condensed">
<% unless @customer.bids.empty? %>
	<% @customer.bids.each do |b| %>
	<tr>
		<td><%= link_to b.created_at.to_date, bid_path(b) %></td>
		<td width="20%"><% if can? :edit, b %><%= link_to "Edit", edit_bid_path(b), class: "btn" %><% end %></td>
		<td width="20%"><% if can? :delete, b %><%= link_to "Delete", bid_path(b), method: :delete, class: "btn" %><% end %></td>
	</tr>
	<% end %>
<% else %>
<tr>
	<td>There are currently no bids for this customer</td>
</tr>
<% end %>
</table>

app/views/customers/_customerform.html.erb
<% provide(:title, "Customer Setup") %>
<div class="row-fluid">

<div class="span8 form-highlight round padding2">
  <h2>Customer Setup</h2>
  <div class="line"></div>
  <span class="required_notification">* Denotes Required Field</span>
  </br>
  <%= simple_form_for(@customer) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name, required: false, input_html: { required: "required"} %>
    <%= f.input :email %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :phone %>
    <%= f.button :submit, class: "submit btn btn-large btn-primary"%>
  <% end %>
</div>

<div class="span4 border round highlight ">
  <h2>Customer Information</h2>
  <h6>Details</h6>
  </br>
  <h3>Note:</h3>
  <p>The information you are entering here will help you to generate invoices and bids with ease.</p>
</div>

</div>

app/views/customers/_customerinfo.html.erb
<table class="table table-bordered table-condensed">
	<tr>
		<td width="20%">Name</td>
		<td><%= @customer.name %></td>
	</tr>
	<tr>
		<td width="20%">Email</td>
		<td><%= @customer.email %></td>
	</tr>
	<tr>
		<td  width="20%">Address</td>
		<td><%= @customer.full_address %></td>
	</tr>
	<tr>
		<td width="20%">Phone Number</td>
		<td><%= @customer.phone %></td>
	</tr>
</table>

app/views/customers/_invoiceinfo.html.erb
<table class="table table-bordered table-condensed">
  <% unless @customer.invoices.empty? %>
    <tr>
      <td>Created At</td>
      <td>Billing Period</td>
      <td>Paid?</td>
    </tr>
    <% @customer.invoices.each do |invoice| %>
    <tr>
      <td><%= link_to invoice.created_at.to_date, invoice_path(invoice)  %></td> 
      <td><%= invoice.billing_start.to_date %> to <%= invoice.billing_end.to_date %></td>
      <td><%= invoice.total_due ? "Yes" : "No" %></td>
      <td><% if can? :edit, invoice %><%= link_to "Edit", edit_invoice_path(invoice), class: "btn" %><% end %></td>
      <td><% if can? :delete, invoice %><%= link_to "Delete", invoice_path(invoice), method: :delete , class: "btn" %><% end %></td>
    </tr>
    <% end %>
  <% else %>
  <tr>
    <td>There are currently no Jobs for this customer</td>
  </tr>
  <% end %>
    </tr>
  </table>

app/views/customers/_jobinfo.html.erb
<table class="table table-bordered table-condensed">
	<% unless @customer.jobs.empty? %>
		<tr>
			<td>Location</td>
			<td>Created At</td>
			<td>Estimated Start Date</td>
			<td colspan="3">Estimated Finish Date</td>
		</tr>
		<% @customer.jobs.each do |job| %>
		<tr>
			<td><%= link_to job.location %></td>
			<td><%= link_to job.created_at.to_date, job_path(job) %></td>
			<td><%= job.start_date.to_date unless job.start_date.nil? %></td>
			<td><%= job.finish_date.to_date unless job.finish_date.nil? %></td>
			<td><% if can? :edit, job %><%= link_to "Edit", edit_job_path(job), class: "btn" %><% end %></td>
			<td><% if can? :delete, job %><%= link_to "Delete", job_path(job), method: :delete , class: "btn" %><% end %></td>
		</tr>
		<% end %>
	<% else %>
	<tr>
		<td>There are currently no Jobs for this customer</td>
	</tr>
	<% end %>
		</tr>
	</table>

app/views/customers/edit.html.erb
<% provide(:title, "Customers") %>
<%= render 'customers/customerform' %>

app/views/customers/index.html.erb
<% provide(:title, "Customers") %>
<table class="table table-bordered table-condensed shadow">
	<th class="header">Customers</th>
	<tr>
		<td>
			<table class="table table-bordered table-condensed">
				<% unless @customers.empty? %>
				<tr>
					<td class="highlight" width="20%"><b>Name</b></td>
					<td class="highlight" colspan="3"><b>Number of Jobs</b></td>
				</tr>
					<% @customers.each do |customer| %>
					<tr>
						<td><%= link_to customer.name, customer_path(customer) %></td>
						<td><%= customer.jobs.count %>
						<td width="20%"><% if can? :edit, customer %><%= link_to "Edit", edit_customer_path(customer), class: "btn" %><% end %></td>
						<td width="20%"><% if can? :delete, customer %><%= link_to "Delete", customer_path(customer), confirm: "You Sure?", class: "btn", method: :delete %><% end %></td>
					</tr>
					<% end %>
					<tr>
            <td colspan="4">
              <div class="digg_pagination">
                  <%= will_paginate @customers, :container => false %>
              </div>
            </td>
          </tr>
				<% else %>
						<tr>
							<td>There are currently no customers</td>
						</tr>
				<% end %>
			</td>
		</tr>
		<tr>
			<td colspan="4"><% if can? :create, Customer.new %><%= link_to "New Customer", new_customer_path, class: "btn" %><% end %></td>
		</tr>
	</table>
</table>

app/views/customers/new.html.erb
<% provide(:title, "Customers") %>
<%= render 'customers/customerform' %>

app/views/customers/show.html.erb
<% provide(:title, "Customers") %>
<table class="table table-bordered table-condensed shadow">
  <th class="header" colspan="3">Customer Page For <%= @customer.name %></th>
  <tr>
    <td>
      <table class="table table-bordered table-condensed">
        <th class="highlight">Customer Information</th>
        <tr>
          <td>
            <%= render 'customers/customerinfo' %>
          </td>
        </tr>
        <th class="highlight">Bid Information</th>
        <tr>
          <td>
            <%= render 'customers/bidinfo' %>
          </td>
        </tr>
        <th class="highlight">Job Information</th>
        <tr>
          <td>     
            <%= render 'customers/jobinfo' %>
          </td>
        </tr>
        <th class="highlight">Invoice Information</th>
        <tr>
          <td>     
            <%= render 'customers/invoiceinfo' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
			
				
				
				