config/routes.rb
Molitum::Application.routes.draw do
  devise_for :users

  root :to => "static_pages#home"

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :companies 
  resources :users
  resources :customers
  resources :quick_links, only: [:create, :destroy]
  resources :time_clocks, only: [:create, :update, :destroy]

  resources :bids do
    resources :bid_items, only: [:create, :destroy], shallow: true
  end
  
  resources :invoices do
    resources :invoice_items, only: [:create, :destroy], shallow: true
  end
  
  resources :jobs do
    resources :job_expenses, only: [:create, :destroy], shallow: true
  end

end

app/views/layouts/_alert.html.erb
<div class="center">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %><button class="close" data-dismiss="alert">×</button></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <a href="#">Molitum</a>
    by Cody Tanner
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact",contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About Us", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div id="logo" class="pull-left">
<%= image_tag "logo.png" %>
</div>
<% unless user_signed_in? %>
  <div id="header-signin-outer">
    <div id="header-signin-inner">
      <%= link_to "Sign In", new_user_session_path, class: "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>
<div id="main_navbar" class="navbar shadow">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav pull-left">
        <li class="brand"><%= yield(:title) %></a></li>
        <li class="divider-vertical"></li>
      </ul>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li class="divider-vertical"></li>
          <ul class="nav nav-pills">
            <li class="dropdown" id="menu1">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">Settings</i>
            <b class="caret"></b></a>
            <ul class="dropdown-menu">
            <li><%= link_to(edit_user_path(current_user)) do %><span><i class="icon-cog"></i>Account Settings</span><% end %></li>
            <li><%= link_to(edit_company_path(current_user.company)) do %><span><i class="icon-cog"></i>Company Settings</span><% end %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="span2">
  <ul class="nav nav-list">
    <% if user_signed_in? %>
      <li class="nav-header">Application</li>
      <% if @title == 'Home' %><li class="active"><% else %><li><% end %></i><%= link_to "Home", root_path %></li>
      <% if @title == 'My Account' %><li class="active"><% else %><li><% end %><%= link_to "My Account", user_path(current_user) %></li>
      <% if @title == 'Employees' %><li class="active"><% else %><li><% end %><%= link_to "Employees", users_path%></li>
      <% if @title == 'Customers' %><li class="active"><% else %><li><% end %><%= link_to "Customers", customers_path%></li>
      <% if @title == 'Jobs' %><li class="active"><% else %><li><% end %><%= link_to "Jobs", jobs_path%></li>
      <% if @title == 'Bids' %><li class="active"><% else %><li><% end %><%= link_to "Bids", bids_path%></li>
      <% if @title == 'Invoices' %><li class="active"><% else %><li><% end %><%= link_to "Invoices", invoices_path%></li>
    <% end %>
    <li class="nav-header">Site Links</li>
    <% if @title == 'Home' %><li class="active"><% else %><li><% end %><a href="/"><i class="icon-home"></i>Home</a></li>
    <% if @title == 'Contact' %><li class="active"><% else %><li><% end %><a href="/contact"><i class="icon-envelope"></i>Contact</a></li>
    <% if @title == 'Help' %><li class="active"><% else %><li><% end %><a href="/help"><i class="icon-question-sign"></i>Help</a></li>
    <% if @title == 'About' %><li class="active"><% else %><li><% end %><a href="/about"><i class="icon-info-sign"></i>About Us</a></li>
  </ul>
</div>

app/views/layouts/_sidebar1.html.erb
<div class="span2">
<div class="round border menu shadow">
  <ul class="nav nav-list">
    <% if user_signed_in? %>
      <li class="nav-header">Application</li>
      <% if current_user.role == "Owner" %>
        <% if yield(:title) == '#{current_user.company.name}' %><li class="active"><% else %><li><% end %>
        <%= link_to(company_path(current_user)) do %><span><i class="icon-star"></i>My Company</span><% end %></li>
      <% end %>
      <% if yield(:title) == "Account For #{current_user.name}" %><li class="active"><% else %><li><% end %>
      <%= link_to(current_user) do %><span><i class="icon-star"></i>My Account</span><% end %></li>
      <% if yield(:title) == 'Employees' %><li class="active"><% else %><li><% end %>
      <%= link_to(users_path) do %><span><i class="icon-user"></i>Employees</span><% end %></li>
      <% if yield(:title) == 'Customers' %><li class="active"><% else %><li><% end %>
      <%= link_to(customers_path) do %><span><i class="icon-user"></i>Customers</span><% end %></li>
      <% if yield(:title) == 'Jobs' %><li class="active"><% else %><li><% end %>
      <%= link_to(jobs_path) do %><span><i class="icon-briefcase"></i>Jobs</span><% end %></li>
      <% if yield(:title) == 'Bids' %><li class="active"><% else %><li><% end %>
      <%= link_to(bids_path) do %><span><i class="icon-folder-open"></i>Bids</span><% end %></li>
      <% if yield(:title) == 'Invoices' %><li class="active"><% else %><li><% end %>
      <%= link_to(invoices_path) do %><span><i class="icon-folder-open"></i>Invoices</span><% end %></li>
    <% end %>
    <li class="nav-header">Site Links</li>
    <% if yield(:title) == 'Home' %><li class="active"><% else %><li><% end %><a href="/"><i class="icon-home"></i>Home</a></li>
    <% if yield(:title) == 'Contact' %><li class="active"><% else %><li><% end %>
                                        <a href="/contact"><i class="icon-envelope"></i>Contact</a></li>
    <% if yield(:title) == 'Help' %><li class="active"><% else %><li><% end %><a href="/help"><i class="icon-question-sign"></i>Help</a></li>
    <% if yield(:title) == 'About' %><li class="active"><% else %><li><% end %><a href="/about"><i class="icon-info-sign"></i>About Us</a></li>
  </ul>
</div>

<div id="recommend" class="border round menu shadow">
<ul class="nav nav-list">
  <li class="nav-header">Recommend Us</li>
    <li>
      <div id="facebook-recommend">
        <div class="fb-like" data-send="false" data-layout="button_count" 
        data-width="100" data-show-faces="false" data-action="recommend" data-font="trebuchet ms"></div>
      </div>
    </li>
    <li>
      <div id="twitter-recommend">
        <a href="https://twitter.com/share" class="twitter-share-button" data-related="molitum" data-hashtags="molitum">Tweet</a>
      </div>
    </li>
    <li>
      <div id="linkedin-recommend">
        <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
        <script type="IN/RecommendProduct" data-company="Molitum" data-product="201714"></script>
      </div>
    </li>
    <li>
      <div id="google-recommend">
        <a href="https://plus.google.com/110022333636213560701?prsrc=3" rel="publisher">
        <img src="//ssl.gstatic.com/images/icons/gplus-32.png" alt="Google+" style="border:0;width:20px;height:20px;"/></a>
      </div>
    </li>
</ul>
</div>

</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_sidebar2.html.erb
<div class="span2 round border shadow menu">
  <% if user_signed_in? %> 
  <ul class="nav nav-list">
    <li class="nav-header">Quick Links</li>
    <li><%= render 'quick_links/quicklinksmodal' %></li>
    <li class="nav-header">Account Links</li>
    <%= render 'time_clocks/timeclockmodal' %>
    <% if current_user.company.nil? %>
      <li><a href="/companies/new" ><i class="icon-map-marker"></i>Add Company</a></li>
    <% end %>
  </ul>
<% else %>
  <h2>Welcome</h2>
    <h6>You're on the right track</h6>
    </br>
    <h3> Why Us? </h3>
    <p>Software suites are bulky and hard to manage. It is with that in mind that we provide the <strong>meat and potatos</strong> of what general contractors really need. We <strong>simplify</strong> your business by giving you all the tools you need for paperwork, so you can spend more time doing what's important.</p>

    <h3> Start Today </h3>
    <p>Click 'Sign up Now!' to start the road to a simpler life.</p>
    <div class="center-text"><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %></div>
<% end %>
</div>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Molitum | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %> 
</head>
<body>
    <div id="main" class="container span10 round shadow" >
      <%= render 'layouts/header' %>
      <div class="row-fluid">
        <%= render 'layouts/sidebar1' %>
        <div class="span8" %>
          <%= render 'layouts/alert' %>
          <%= yield %>
        </div>
        <%= render 'layouts/sidebar2' %>
      </div>
    </div> 
  <div class="navbar navbar-bottom center span10">
    <%= render 'layouts/footer' %> 
  </div>
</body>
</html>